# Generated by Django 5.1.4 on 2025-01-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_short_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_cv',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
    ]
