# Generated by Django 5.1.4 on 2025-01-16 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_about_me_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.workexperience'),
        ),
        migrations.CreateModel(
            name='WorkExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='users.workexperience')),
            ],
        ),
    ]
